export const tracks = [
  'Acorn Heights',
  'Airship Fortress',
  'Boo Cinema',
  'Bowsers Castle',
  'Cheep Cheep Falls',
  'Choco Mountain',
  'Crown City',
  'Dandelion Depths',
  'Desert Hills',
  'Dino Dino Jungle',
  'DK Pass',
  'DK Spaceport',
  'Dry Bones Burnout',
  'Faraway Oasis',
  'Great ? Block Ruins',
  'Koopa Troopa Beach',
  'Mario Bros. Circuit',
  'Mario Circuit',
  'Moo Moo Meadows',
  'Peach Beach',
  'Peach Stadium',
  'Rainbow Road',
  'Salty Salty Speedway',
  'Shy Guy Bazaar',
  'Sky-High Sundae',
  'Starview Peak',
  'Toads Factory',
  'Wario Stadium',
  'Warios Galleon',
  'Whistlestop Summit',
];
